[project]
name = "local-utils-mcp"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.11"
dependencies = [
    "beautifulsoup4>=4.15.0",
    "fastmcp[apps]>=3.4.4",
    "httpx>=0.28.1",
    "msal>=1.37.0",
    "openpyxl>=3.1.4",
    "requests>=2.34.2",
]
